### ISSUE TITLE
find rackspace database

### ISSUE THREAD

**Issue by sporkius** [NeuronRobotics/NeuronRobotics.github.io#32]
find the rackspace database.

**Comment by madhephaestus** [comment]
Make static page availible to everyone on the local network. Link here to close issue.

**Comment by acamilo** [comment]
Can be found here. unzip and open the index.html
http://192.168.3.6:3000/wiki.neuronrobotics.com.zip
http://192.168.3.6:3000/www.neuronrobotics.com.zip
