### ISSUE TITLE
Generalized landing page like the Squarespace landing

### ISSUE THREAD

**Issue by madhephaestus** [NeuronRobotics/NeuronRobotics.github.io#38]
When you go directly to the base website, there should be a more generalized landing page with indexes into things users want and need.

**Comment by madhephaestus** [comment]
The landing page should be:
* Create a wiki page that users see when they go to Neuronrobotics.github.io
* There should be nothing on it at the moment
* The turorials should be moved to a tab at the top
* All tabs from the original landing page should be represented.

**Comment by acamilo** [comment]
Fixed first 3. creating an issue for the last one.

**Comment by madhephaestus** [comment]
http://neuronrobotics.github.io/ still goes to the tutorials page.
