### ISSUE TITLE
Need Video Links

### ISSUE THREAD

**Issue by sporkius** [NeuronRobotics/NeuronRobotics.github.io#41]
Need video links for issue #25

**Comment by madhephaestus** [comment]
Tutorials: https://www.youtube.com/watch?v=NTe2ofn-m34&list=PL7668517BD22B5BA1

**Comment by madhephaestus** [comment]
Robots: https://www.youtube.com/watch?v=dt8qPkFheb4 
https://www.youtube.com/watch?v=w1dtg3IYqHM
https://www.youtube.com/watch?v=ZRUoMjDTQ4Q
https://www.youtube.com/watch?v=g_3gD6SjZqk
Other Projects: 
https://www.youtube.com/watch?v=yaBxnpRX3dA&list=PL0B960B190153C888

**Comment by madhephaestus** [comment]
New NR Robots not yet done: https://www.youtube.com/watch?v=b0-EFWNfIOE
https://www.youtube.com/watch?v=6OR8vLNzWdo
https://www.youtube.com/watch?v=tBLrWYLtnWk
https://www.youtube.com/watch?v=9pQGROqdgow
