### ISSUE TITLE
Make a simple intro to programming tutorial

### ISSUE THREAD

**Issue by madhephaestus** [NeuronRobotics/NeuronRobotics.github.io#59]
Make a tutorial directory with the simplest basics of programming.

**Comment by MrMepper** [comment]
What are the topics that you would like to cover for this?
Simple intros could just include basic mathematics and assigning variables, but it could implement loops and other subjects as well.

**Comment by madhephaestus** [comment]
That sounds great, like a Java 101, even assuming the persoing going through it would know nothing about programming at all. I always like to reference the way OpenScad documents its api as good, understandable presentation of something obsqure like an api design http://www.openscad.org/cheatsheet/

it also references deeper documentation with hyperlinked examples. THis can be a way to pull in existing web documentation for deeper concepts maybe?

**Comment by MrMepper** [comment]
I really enjoy the hyperlinked examples. It reminds me of the way The Odin Project goes about teaching full stack development ([for example](http://www.theodinproject.com/web-development-101/how-does-the-web-work)).

I do have a few questions about how the tutorial will go about:

1. Should the tutorial include instructions for setting up the Java Environment?

2. What do you think in terms of creating simple assignments for students that implement the materials learned from that section, as well as previous sections?

3. At what point does simple stop being "simple"? Should the student learn about subjects such as inheritance, interfaces, and importing other classes, or should we stick data types, variables, and the like?


More on question 3. I was searching around for "Java 101" courses that we could use possibly as a framework for presentation and found [this](http://code.tutsplus.com/courses/introduction-to-computer-programming-with-java-101).

I was thinking, referring back to the above link, that The Basics onwards would be a good framework for the tutorial. Subject to change for some lessons of course.

**Comment by madhephaestus** [comment]
Ooo, i like that Odin model, i had not actually looked at that before!

1) No, because that's what BowlerStudio *is*. If you use github gist to embed code snipits, the compiler and runtime inside the BowlerStudio automatically compile it to a class file, and set it up to be run by clicking the run button. Advanced users would go on to learn an IDE like eclipse, and thats where they will learn that. 

2) I like the assignments idea, im working on a tutorial for forking code and making changes. THis would be a nice application of that!

3) Start with the really simple basics, like what is a computer and how do they do what they do, that gives framing for data types and math. Then introduce boolean loggic and conditional statments, then introduce variables, and arrays, so you can do loops. Id say end with "make your own datatype" and introduce the basics of objects. 

I like the idea of liking into that java 101, but i do not like the order it does things. One of the main goals (for me anyway) for BowlerStudio it to make the process of programming easier, so the introduction to java and its structure is out of place. Also, since it focues so heavily on Java, it puts objects ahead of the code structure. We have the opportunity to avoid that heavy conceptual abstraction as a frontload, and eventually build up to it. Let me know if you dont think this is a good approach, this is all in flux at this point.

**Comment by madhephaestus** [comment]
@RPBruiser are you working with @MrMepper ?

**Comment by RPBruiser** [comment]
I am not. I simply saw this as an open source project looking for some help while I was on reddit.

**Comment by madhephaestus** [comment]
Hey, for the structure of each tutorial page, check out this example from the robotics tutorials. http://neuronrobotics.com/Java-Code-Library/Digital-Input-Example-Simple/

source:

https://github.com/NeuronRobotics/NeuronRobotics.github.io/blob/source/content/Java-Code-Library/Digital-Input-Example-Simple.md

It has a single code snippet per page, this lets bowler studio find it and run the code snippet. The file name for the code snippet should end in .java or  .groovy.

**Comment by MrMepper** [comment]
Just for clarification, each tutorial page should have ONLY ONE code snippet?
I wasn't entirely sure if that was the case when I was editing the tutorial, and will make any changes needed if that is the case.
I was using the source pages as a basis, but I'm just now noticing that each one only has a single code snippet.

**Comment by madhephaestus** [comment]
yeah, ill add in the futur the ability to scrape all the gists visable, but for now its just the one per page.
