### ISSUE TITLE
Issue compiling locally

### ISSUE THREAD

**Issue by MrMepper** [NeuronRobotics/NeuronRobotics.github.io#63]
I'm having issues accessing the localhost:3000 when running "nanoc view & guard" in the command line.

I'm getting a white screen with "File not found: /"

The command line runs as follows:

    C:\Users\Chris\IdeaProjects\NeuronRobotics.github.io>nanoc view & guard
    WARN: Unresolved specs during Gem::Specification.reset:
          cri (~> 2.3)
    WARN: Clearing out unresolved specs.
    Please report a bug if this causes problems.
    [2015-06-26 21:34:52] INFO  WEBrick 1.3.1
    [2015-06-26 21:34:52] INFO  ruby 2.2.2 (2015-04-13) [i386-mingw32]
    [2015-06-26 21:34:52] INFO  WEBrick::HTTPServer#start: pid=7232 port=3000

When attempting to connect I get this:

    127.0.0.1 - - [26/Jun/2015 21:35:10] "GET / HTTP/1.1" 404 18 0.0000
    GamingPC - - [26/Jun/2015:21:35:10 Central Daylight Time] "GET / HTTP/1.1" 404 18
    - -> /

This is done on a windows 7 machine.

**Comment by MrMepper** [comment]
Screenshot of issue:

![untitled](https://cloud.githubusercontent.com/assets/8658239/8390197/8793c3ee-1c4d-11e5-95e3-6d176fb33c4d.png)

**Comment by acamilo** [comment]
Can you try this?
`sudo apt-get install bundler`        (if you dont have it already)
cd into Neuronrobotics.github.io
`sudo bundle install`


you should see this
```
:~/git/NeuronRobotics.github.io$ sudo bundle install
Fetching source index from http://production.cf.rubygems.org/
Installing rake (10.4.2) 
Installing rack (1.5.2) 
Installing adsf (1.2.0) 
Installing hitimes (1.2.2) 
Installing timers (4.0.1) 
Installing celluloid (0.16.0) 
Installing coderay (1.1.0) 
Installing colored (1.2) 
Installing cri (2.6.1) 
Installing diff-lcs (1.2.5) 
Installing ffi (1.9.6) 
Installing formatador (0.2.5) 
Installing rb-fsevent (0.9.4) 
Installing rb-inotify (0.9.5) 
Installing listen (2.8.3) 
Installing lumberjack (1.0.9) 
Installing method_source (0.8.2) 
Installing slop (3.6.0) 
Installing pry (0.10.1) 
Installing thor (0.19.1) 
Installing guard (2.10.2) 
Installing nanoc (3.7.4) 
Installing guard-nanoc (1.0.3) 
Installing kramdown (1.5.0) 
Installing rainbow (2.0.0) 
Installing rspec-support (3.1.2) 
Installing rspec-core (3.1.7) 
Installing rspec-expectations (3.1.2) 
Installing rspec-mocks (3.1.3) 
Installing rspec (3.1.0) 
Using bundler (1.3.5) 
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

then try nanoc view & guard

**Comment by MrMepper** [comment]
C:\Users\Chris\IdeaProjects\NeuronRobotics.github.io>bundle install
    Using rake 10.4.2
    Using rack 1.5.2
    Using adsf 1.2.0
    Using hitimes 1.2.2
    Using timers 4.0.1
    Using celluloid 0.16.0
    Using coderay 1.1.0
    Using colored 1.2
    Using cri 2.6.1
    Using diff-lcs 1.2.5
    Using ffi 1.9.6
    Using formatador 0.2.5
    Using rb-fsevent 0.9.4
    Using rb-inotify 0.9.5
    Using listen 2.8.3
    Using lumberjack 1.0.9
    Using method_source 0.8.2
    Using slop 3.6.0
    Using win32console 1.3.2
    Using pry 0.10.1
    Using thor 0.19.1
    Using guard 2.10.2
    Using nanoc 3.7.4
    Using guard-nanoc 1.0.3
    Using kramdown 1.5.0
    Using rainbow 2.0.0
    Using rspec-support 3.1.2
    Using rspec-core 3.1.7
    Using rspec-expectations 3.1.2
    Using rspec-mocks 3.1.3
    Using rspec 3.1.0
    Using bundler 1.10.3
    Bundle complete! 9 Gemfile dependencies, 32 gems now installed.
    Use `bundle show [gemname]` to see where a bundled gem is installed.
     
    C:\Users\Chris\IdeaProjects\NeuronRobotics.github.io>nanoc view & guard
    [2015-06-28 14:36:19] INFO  WEBrick 1.3.1
    [2015-06-28 14:36:19] INFO  ruby 2.2.2 (2015-04-13) [i386-mingw32]
    [2015-06-28 14:36:19] INFO  WEBrick::HTTPServer#start: pid=6688 port=3000
    127.0.0.1 - - [28/Jun/2015 14:36:22] "GET / HTTP/1.1" 404 18 0.0010
    GamingPC - - [28/Jun/2015:14:36:22 Central Daylight Time] "GET / HTTP/1.1" 404 18
    - -> /

Issue still present. Have attempted to use the commands one at a time, however the command prompt becomes locked after entering "nanoc view"

**Comment by MrMepper** [comment]
I can switch development to my Ubuntu machine though. If it is a windows issue, it is only a minor setback.

**Comment by acamilo** [comment]
pop open another shell, go to the project directory and run the other command. lets try that before we switch to something else

**Comment by MrMepper** [comment]
There seems to be an issue with hitimes version 1.2.2

     C:\Users\Chris\IdeaProjects\NeuronRobotics.github.io>guard
     C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- hitimes/hitimes (LoadError)
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/hitimes-1.2.2-x86-mingw32/lib/hitimes.rb:37:in `rescue in <top (required)>'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/hitimes-1.2.2-x86-mingw32/lib/hitimes.rb:32:in `<top (required)>'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/timers-4.0.1/lib/timers/group.rb:4:in `<top (required)>'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/timers-4.0.1/lib/timers.rb:4:in `<top (required)>'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/receivers.rb:3:in `<top (required)>'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid.rb:475:in `<top (required)>'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/listen-2.8.3/lib/listen.rb:1:in `<top (required)>'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/guard-2.10.2/lib/guard.rb:2:in `<top (required)>'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/guard-2.10.2/bin/guard:3:in `<top (required)>'
        from C:/Ruby22/bin/guard:23:in `load'
        from C:/Ruby22/bin/guard:23:in `<main>'

**Comment by MrMepper** [comment]
It seems to actually be an issue with windows and hitimes as of yet not releasing a fat binary for ruby version 2.2

Reference:
copiousfreetime/hitimes#40
copiousfreetime/hitimes#39

**Comment by acamilo** [comment]
Guard just watches the directiry and recompiles the site on changes. you should still be able to run `nanoc compile` to update it and then `nanoc view` to view it every time you want to see the results to your changes.
